when:
  - author:
      teamIs:
        - rubik
      ignore:
        nameIs:
    assign:
      teams:
        - rubik
  - author:
      teamIs:
        - woo-fse
      ignore:
        nameIs:
    assign:
      teams:
        - woo-fse
