language: php

sudo: false

# Test main supported versions of PHP against latest WP.
php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

# Additional tests against stable PHP (min recommended version is 5.6) and past supported versions of WP
# and code coverage report.
matrix:
  fast_finish: true
  include:
  - php: 5.3
    dist: precise
  - php: 5.2
    dist: precise
  - php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1
  - php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1
  allow_failures:
  - env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - npm install
  - export NODE_CONFIG_DIR="./tests/e2e-tests/config"
  - "./tests/e2e-tests/scripts/wp-serverpilot-delete.js"
  - "./tests/e2e-tests/scripts/wp-serverpilot-init.js"
  - scp -o "StrictHostKeyChecking no" tests/e2e-tests/scripts/git-woo.sh serverpilot@wp-e2e-tests.pw:~serverpilot/git-woo.sh
  - scp -o "StrictHostKeyChecking no" tests/e2e-tests/data/e2e-db.sql serverpilot@wp-e2e-tests.pw:~serverpilot/e2e-db.sql
  - ssh -o "StrictHostKeyChecking no" serverpilot@wp-e2e-tests.pw ~serverpilot/git-woo.sh wordpress-${TRAVIS_PULL_REQUEST_SHA:0:20}

script:
  - bash tests/bin/phpunit.sh
  - bash tests/bin/phpcs.sh
  - npm run test

after_script:
  - bash tests/bin/travis.sh after
  - "./tests/e2e-tests/scripts/jetpack/wp-serverpilot-delete.js"

# Specifies that Travis should create builds for master and release branches and also tags.
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^release\//
    - try/e2e-CI
