
name: Mirrors
on:
  push:
    branches: [ 'test/build-prod-repo-on-push' ]
jobs:
    mirror:
        name: Push to Mirror
        runs-on: ubuntu-latest
        steps:
            - name: Create directories
              run: |
                  mkdir -p tmp/woocommerce-build
                  mkdir -p monorepo

            - name: Checkout monorepo
              uses: actions/checkout@v2
              with:
                  path: monorepo

            - name: Extract and replace WooCommerce zip.
              working-directory: tmp/woocommerce-build
              run: |
                  mkdir -p woocommerce/woocommerce-production
                  touch woocommerce/woocommerce-production/README.md
                  echo "# WooCommerce Production (TEST)" >> woocommerce/woocommerce-production/README.md

            - name: Set up for mirror
              working-directory: tmp/woocommerce-build
              run: |
                  touch mirrors.txt
                  echo "woocommerce/woocommerce-production" >> mirrors.txt
                  GIT_SLUG=woocommerce-production
                  
            - name: Push to mirror
              uses: Automattic/action-push-to-mirrors@v1
              with:
                  source-directory: ${{ github.workspace }}/monorepo
                  token: ${{ secrets.API_TOKEN_GITHUB }}
                  username: matticbot
                  working-directory: ${{ github.workspace }}/tmp/woocommerce-build
              timeout-minutes: 5  # 2021-01-18: Successful runs seem to take about half a minute.
