name: Lint and tests for JS packages and woocommerce-admin/client

on:
  pull_request:
    paths:
      - 'packages/js/**/**'
      - 'plugins/woocommerce-admin/client/**'
      - '!**.md'
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test-js:
    name: Lint and Test JS
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - uses: ./.github/actions/cache-deps
        with:
          workflow_name: pr-lint-test-js
          workflow_cache: ${{ secrets.WORKFLOW_CACHE }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install and Build
        uses: ./.github/actions/install-build

      - name: Lint
        run: |
          pnpm nx build woocommerce-admin
          pnpm nx lint woocommerce-admin
          pnpm nx lint:js-packages woocommerce-admin

      - name: Test
        run: |
          pnpm nx build woocommerce-admin
          pnpm nx test woocommerce-admin
          pnpm nx test:packages woocommerce-admin
