name: Run lint checks potentially affecting projects across the monorepo
on:
    pull_request:
        paths:
            - '.github/workflows/pr-lint-monorepo.yml'
            - 'packages/**'
            - 'plugins/**'
            - '!**/changelog/**'
        branches:
            - 'trunk'

concurrency:
    group: changelogger-${{ github.event_name }}-${{ github.ref }}
    cancel-in-progress: true

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
    changelogger_used:
        name: Changelogger use
        runs-on: ubuntu-20.04
        permissions:
            contents: read
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  # The package has majority of composer-deps, therefore referencing it
                  pull-package-composer-deps: '@woocommerce/plugin-woocommerce'

            - name: Check change files are touched for touched projects
              env:
                  BASE: ${{ github.event.pull_request.base.sha }}
                  HEAD: ${{ github.event.pull_request.head.sha }}
              run: php tools/monorepo/check-changelogger-use.php --debug "$BASE" "$HEAD"

            - name: Run changelog validation
              run: pnpm --recursive --parallel --stream changelog validate
