name: Run smoke tests against pull request.
on:
  pull_request:
    branches:
      - trunk
    types:
      - labeled
jobs:
  prcheck:
    name: Smoke test a pull request.
    if: "${{ contains(github.event.label.name, 'run: smoke tests') }}"
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
            access_token: ${{ github.token }}

      - name: Create dirs.
        run: |
          mkdir -p code/woocommerce
          mkdir -p package/woocommerce
          mkdir -p tmp/woocommerce
          mkdir -p node_modules

      - name: Checkout code.
        uses: actions/checkout@v2
        with:
          path: package/woocommerce

      - name: Install prerequisites.
        working-directory: package/woocommerce/plugins/woocommerce
        id: installation
        run: |
          npm install -g pnpm
          pnpm install
          pnpm nx composer-install-no-dev woocommerce
          pnpm nx build-assets woocommerce
          pnpm install jest

      - name: Run smoke test.
        working-directory: package/woocommerce/plugins/woocommerce
        if: always()
        env:
          SMOKE_TEST_URL: ${{ secrets.SMOKE_TEST_URL }}
          SMOKE_TEST_ADMIN_USER: ${{ secrets.SMOKE_TEST_ADMIN_USER }}
          SMOKE_TEST_ADMIN_PASSWORD: ${{ secrets.SMOKE_TEST_ADMIN_PASSWORD }}
          SMOKE_TEST_ADMIN_USER_EMAIL: ${{ secrets.SMOKE_TEST_ADMIN_USER_EMAIL }}
          SMOKE_TEST_CUSTOMER_USER: ${{ secrets.SMOKE_TEST_CUSTOMER_USER }}
          SMOKE_TEST_CUSTOMER_PASSWORD: ${{ secrets.SMOKE_TEST_CUSTOMER_PASSWORD }}
          WC_E2E_SCREENSHOTS: 1
          E2E_RETEST: 1
          E2E_SLACK_TOKEN: ${{ secrets.SMOKE_TEST_SLACK_TOKEN }}
          E2E_SLACK_CHANNEL: ${{ secrets.SMOKE_TEST_SLACK_CHANNEL }}
          UPDATE_WC: 1
          DEFAULT_TIMEOUT_OVERRIDE: 120000
        run: |
          pnpx wc-e2e test:e2e tests/e2e/specs/smoke-tests/update-woocommerce.js

      - name: Post Smoke tests results comment on PR
        if: always()
        uses: actions/github-script@v5
        env:
          TITLE: 'Smoke Test Results'
          SMOKE_TEST_URL: ${{ secrets.SMOKE_TEST_URL }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require( './package/woocommerce/packages/js/e2e-environment/bin/post-results-to-github-pr.js' )
            await script({github, context})

      - name: Run E2E tests.
        working-directory: package/woocommerce/plugins/woocommerce
        if: always()
        env:
          SMOKE_TEST_URL: ${{ secrets.SMOKE_TEST_URL }}
          SMOKE_TEST_ADMIN_USER: ${{ secrets.SMOKE_TEST_ADMIN_USER }}
          SMOKE_TEST_ADMIN_PASSWORD: ${{ secrets.SMOKE_TEST_ADMIN_PASSWORD }}
          SMOKE_TEST_ADMIN_USER_EMAIL: ${{ secrets.SMOKE_TEST_ADMIN_USER_EMAIL }}
          SMOKE_TEST_CUSTOMER_USER: ${{ secrets.SMOKE_TEST_CUSTOMER_USER }}
          SMOKE_TEST_CUSTOMER_PASSWORD: ${{ secrets.SMOKE_TEST_CUSTOMER_PASSWORD }}
          WC_E2E_SCREENSHOTS: 1
          E2E_RETEST: 1
          E2E_SLACK_TOKEN: ${{ secrets.SMOKE_TEST_SLACK_TOKEN }}
          E2E_SLACK_CHANNEL: ${{ secrets.SMOKE_TEST_SLACK_CHANNEL }}
          UPDATE_WC: 1
          DEFAULT_TIMEOUT_OVERRIDE: 120000
        run: |
          pnpx wc-e2e test:e2e

      - name: Post E2E tests results comment on PR
        if: always()
        uses: actions/github-script@v5
        env:
          TITLE: 'E2E Test Results'
          SMOKE_TEST_URL: ${{ secrets.SMOKE_TEST_URL }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require( './package/woocommerce/packages/js/e2e-environment/bin/post-results-to-github-pr.js' )
            await script({github, context})

      - name: Remove label from pull request.
        if: |
          always() 
           && contains( github.event.pull_request.labels.*.name, format('run{0} smoke tests', ':')) 
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'run: smoke tests'
