name: WooCommerce Beta Tester Release
permissions: {}

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'The version number for the release'
                required: true

jobs:
    release:
        name: Run release scripts
        runs-on: ubuntu-20.04
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                install: '@woocommerce/plugin-woocommerce'
                build: '@woocommerce/plugin-woocommerce'
                pull-package-deps: '@woocommerce/plugin-woocommerce-beta-tester'

            - name: Lint
              working-directory: plugins/woocommerce-beta-tester
              run: composer run phpcs

            - name: Build WooCommerce Beta Tester Zip
              working-directory: plugins/woocommerce-beta-tester
              run: pnpm build:zip

            - name: Create release
              id: create_release
              uses: woocommerce/action-gh-release@master
              with:
                  tag_name: wc-beta-tester-${{ inputs.version }}
                  name: WooCommerce Beta Tester Release ${{ inputs.version }}
                  draft: false
                  files: plugins/woocommerce-beta-tester/woocommerce-beta-tester.zip
