name: Smoke k6 test daily
on: push
jobs:
  update-woocommerce:
    name: Run k6 smoke test using trunk on ext site.
    runs-on: ubuntu-18.04
    steps:

      - name: Create dirs.
        run: |
              mkdir -p code/woocommerce
              mkdir -p package/woocommerce
              mkdir -p tmp/woocommerce
              mkdir -p node_modules

      - name: Checkout code.
        uses: actions/checkout@v2
        with:
          path: package/woocommerce
          ref: trunk

      - name: Install prerequisites.
        working-directory: package/woocommerce/plugins/woocommerce
        run: |
          npm install -g pnpm
          pnpm install
          pnpm nx composer-install-no-dev woocommerce
          pnpm nx build-assets woocommerce
          pnpm install jest
          
      - name: Run e2e woocommerce update.
        working-directory: package/woocommerce/plugins/woocommerce
        env:
          SMOKE_TEST_URL: ${{ secrets.SMOKE_TEST_PERF_URL }}
          SMOKE_TEST_ADMIN_USER: ${{ secrets.SMOKE_TEST_PERF_ADMIN_USER }}
          SMOKE_TEST_ADMIN_PASSWORD: ${{ secrets.SMOKE_TEST_PERF_ADMIN_PASSWORD }}
          SMOKE_TEST_ADMIN_USER_EMAIL: ${{ secrets.SMOKE_TEST_ADMIN_USER_EMAIL }}
          SMOKE_TEST_CUSTOMER_USER: ${{ secrets.SMOKE_TEST_CUSTOMER_USER }}
          SMOKE_TEST_CUSTOMER_PASSWORD: ${{ secrets.SMOKE_TEST_CUSTOMER_PASSWORD }}
          WC_E2E_SCREENSHOTS: 1
          E2E_RETEST: 1
          E2E_SLACK_TOKEN: ${{ secrets.SMOKE_TEST_SLACK_TOKEN }}
          E2E_SLACK_CHANNEL: ${{ secrets.SMOKE_TEST_SLACK_CHANNEL }}
          UPDATE_WC: 1
          DEFAULT_TIMEOUT_OVERRIDE: 120000
        run: |
          pnpx wc-e2e test:e2e tests/e2e/specs/smoke-tests/update-woocommerce.js
      - name: debugging
        if: always()
        working-directory: package/woocommerce/plugins/woocommerce 
        run: |
          pwd
          ls
          ls tests/e2e
          echo "about to check plugins folder"
          ls tests/e2e/plugins
