name: Synchronize Dependencies with syncpack
on:
  # Run whenever a pull request is updated
  pull_request:
    branches:
      - trunk
    paths:
      - '**/package.json'

permissions: {}

jobs:
  syncpack:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: syncpack
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      
      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 'Install Syncpack'
        run: npm install -g syncpack@^8.2.4
        
      - name: 'List Mismatches'
        run: syncpack list-mismatches
        
      - name: 'Explain Remedy'
        if: failure()
        run: |
          echo "Dependency version mismatch detected. This can usually be fixed automatically by updating the pinned version in \`.syncpackrc\` and then running: \`pnpm run sync-dependencies\`"
          exit 1
