name: Send a Slack notification when an Issue contains an assignment to Solaris

on:
  issues:
    types: [labeled]

permissions: {}

jobs:
  send-slack-notification-when-issue-contains-team-solaris-label:
    if: "${{ github.event.label.name == 'team: Solaris' }}"
    runs-on: ubuntu-20.04
    steps:
      - name: Wait 2 minutes for other labelling jobs to finish
        run: sleep 2m
        shell: bash

      # Notify Slack Step
      - name: Notify Slack
        uses: archive/github-actions-slack@d9dae40827adf93bddf939db6552d1e392259d7d
        id: notify
        with:
            slack-bot-user-oauth-access-token: ${{ secrets.TEST_ASSISTANCE_BOT_TOKEN }}
            slack-channel: ${{ secrets.TEAM_SOLARIS_ISSUE_ANALYSIS_CHANNEL }}
            slack-text: |
                <${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>
                *Labels:* ${{ join(github.event.issue.labels.*.name, ', ') }}
                Please review this issue to check if it has been correctly assigned to Solaris.
            slack-optional-unfurl_links: false
            slack-optional-unfurl_media: false
