name: Test Send a Slack notification when a PR contains rest api changes

on:
  pull_request_target:
    types: [labeled]

permissions: {}

jobs:
  send-slack-notification-when-pr-contains-rest-api-changes:
    if: "${{ github.event.label.name == 'test: label' && (github.event.pull_request.state == 'open' || github.event.pull_request.merged) }}"
    runs-on: ubuntu-20.04
    steps:
      - name: Wait 1 minute for other labelling jobs to finish
        run: sleep 1m
        shell: bash

#... previous steps...

      - name: Calculate test date
        id: calculate_date
        run: |
          #!/bin/bash
          
          # Get the day of the week of the merged PR (0 for Sunday, 1 for Monday, etc.)
          MERGE_DAY_OF_WEEK=$(date -u -d "${{ github.event.pull_request.merged_at }}" +"%u")
          
          # Calculate days until the next Wednesday after the merge
          DAYS_UNTIL_NEXT_WEDNESDAY=$(( (3 - MERGE_DAY_OF_WEEK + 7) % 7 ))
          DAYS_UNTIL_NEXT_THURSDAY=$((DAYS_UNTIL_NEXT_WEDNESDAY + 1))
          
          # Calculate the date for the next Thursday after the merge
          THURSDAY_AFTER_MERGE=$(date -u -d "${{ github.event.pull_request.merged_at }} + $DAYS_UNTIL_NEXT_THURSDAY days" +"%Y-%m-%d")
          NEXT_THURSDAY=$(date -u -d "${{ github.event.pull_request.merged_at }} + $(($DAYS_UNTIL_NEXT_THURSDAY + 7)) days" +"%Y-%m-%d")
          
          CURRENT_TIMESTAMP=$(date -u +"%s")
          WEDNESDAY_AFTER_MERGE_TIMESTAMP=$(date -u -d "${{ github.event.pull_request.merged_at }} + $DAYS_UNTIL_NEXT_WEDNESDAY days" +"%s")
          
          if [[ "$WEDNESDAY_AFTER_MERGE_TIMESTAMP" -le "$CURRENT_TIMESTAMP" ]]; then
            TEST_DATE_MESSAGE="Can be tested from: Thursday, $THURSDAY_AFTER_MERGE"
          else
            TEST_DATE_MESSAGE="Can be tested from: Thursday, $NEXT_THURSDAY"
          fi
          echo "TEST_DATE_MESSAGE=${TEST_DATE_MESSAGE}" >> $GITHUB_ENV

#... following steps...


      # Notify Slack Step
      - name: Notify Slack
        uses: archive/github-actions-slack@d9dae40827adf93bddf939db6552d1e392259d7d
        id: notify
        with:
            slack-bot-user-oauth-access-token: ${{ secrets.TEST_ASSISTANCE_BOT_TOKEN }}
            slack-channel: ${{ secrets.TEST_SLACK_CHANNEL }}
            slack-text: |
                <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>
                *Labels:* ${{ join(github.event.pull_request.labels.*.name, ', ') }}
                *Milestone:* <${{ github.event.pull_request.milestone.html_url }}|${{ github.event.pull_request.milestone.title }}>
                *${{ env.TEST_DATE_MESSAGE }}*
            slack-optional-unfurl_links: false
            slack-optional-unfurl_media: false
